{{- if .Values.fcrepo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyrax.fcrepo.fullname" . }}
  labels:
{{ include "hyrax.labels" . | indent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  DATABASE_HOST: {{ include "fcrepo.postgresql.fullname" . | b64enc }}
  JAVA_OPTS: {{ printf "-Dfcrepo.modeshape.configuration=\"classpath:/config/jdbc-postgresql/repository.json\" -Dfcrepo.postgresql.host=\"%s\" -Dfcrepo.postgresql.username=\"%s\" -Dfcrepo.postgresql.password=\"%s\" -Dfcrepo.object.directory=\"/data/objects\" -Dfcrepo.binary.directory=\"/data/binaries\"" ( include "fcrepo.postgresql.fullname" . ) .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword | b64enc }}
{{- end }}
