apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyrax.fullname" . }}
  labels:
{{ include "hyrax.labels" . | indent 4 }}
type: Opaque
data:
  SECRET_KEY_BASE: {{ randAlphaNum 20 | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s/%s?pool=5" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "hyrax.postgresql.fullname" .) .Values.postgresql.postgresqlDatabase | b64enc }}
  {{- end }}
